server:
  port: 8080
spring:
  application:
    name: pagination-application
  profiles:
    active: local
  datasource:
    url: jdbc:sqlserver://localhost:1461;databaseName=test;trustServerCertificate=true
    userName: sa
    password: ${mssql_pwd}
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springdoc:
  swagger-ui:
    path: /docs.html